let data = [
  {
    id: 1,
    name: "Anime APP",
    details: `Anime app Coolest thing ever`,
    img: "facebook.jpg",
    backgroundImg: "AnimeApp.jpg",
    Technology: ["React", "HTML5", "CSS3"],
    Link: "https://young-falls-71941.herokuapp.com/",
    Git: "https://github.com/tevelmantsur/Movies-APP--react",
  },
  {
    id: 2,
    name: "Apartments APP",
    details: `Anime app Coolest thing ever`,
    img: "facebook.jpg",
    backgroundImg: "Apartments.png",
    Technology: [
      "NextJS",
      "HTML5",
      "CSS3",
      "MongoDB",
      "Puppeteer",
      "Material-UI",
    ],
    Link: "https://next-js-apartments.vercel.app/",
    Git: "https://github.com/tevelmantsur/NextJs-Apartments",
  },
  {
    id: 3,
    name: "Tevel Develepoment",
    details: `Anime app Coolest thing ever`,
    img: "facebook.jpg",
    backgroundImg: "TevelDEV.png",
    Technology: ["React", "HTML5", "CSS3"],
    Git: "https://github.com/tevelmantsur/Portfolio-React",
  },
  {
    id: 4,
    name: "Tree APP",
    details: `Anime app Coolest thing ever`,
    img: "facebook.jpg",
    backgroundImg: "MagenTrees.png",
    mobile: true,
    Technology: ["React-Native", "Expo", "LiteSQL"],
  },
  {
    id: 5,
    name: "HELEN TZUR",
    details: "הדרכה אישית וקבוצית",
    img: "facebook.jpg",
    backgroundImg: "HelenPage.png",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
  },
  {
    id: 6,
    name: "DUBI BUS",
    details: "הסעות לכל הארץ",
    img: "dubibus.png",
    backgroundImg: "dubibus.png",
    Technology: ["Wordpress", "HTML5"],
    Link: "https://dubbus.co.il/",
  },
  {
    id: 7,
    name: "DUBI TOURS",
    details: "הסעות לכל הארץ",
    img: "dubitours.png",
    backgroundImg: "dubitours.png",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
    Link: "https://dubitours.co.il/",
  },
  {
    id: 8,
    name: "SELVA RESORT",
    details: "ווילות בקוסטה ריקה",
    img: "selvaresort.png",
    backgroundImg: "selvaresort.png",
    Technology: ["Wix", "HTML5", "CSS3"],
    Link: "https://www.selvaresort.com/",
  },
  {
    id: 9,
    name: "SUPER FIT",
    details: "אתר תזונה וכושר",
    img: "24fitclub.png",
    backgroundImg: "SuperfitPage.jpg",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
  },
  {
    id: 10,
    name: "CANNA YAGODA",
    details: "קנאביס",
    img: "cannayagoda.png",
    backgroundImg: "CannayagodaPage.jpg",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
    Link: " https://cannayagoda.co.il/?lang=en",
  },
  {
    id: 11,
    name: "FLYCHIPS",
    details: "'ציפים לעולם",
    img: "flychips.png",
    backgroundImg: "FlychipsPage.png",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
    Link: "https://flychips.com/",
  },
  {
    id: 12,
    name: "Yeshivot APP",
    details: `Anime app Coolest thing ever`,
    img: "facebook.jpg",
    backgroundImg: "YeshivotAPP.jpg",
    mobile: true,
    Technology: ["React-Native", "Expo", "FireBase"],
  },

  {
    id: 13,
    name: "FC CORP Electronics",
    details: `C CORP. specializes in electronic components supply solutions as well as stock management for companies.
    The company is a global company in continuous growth and operates in countries around the world.`,
    img: "facebook.jpg",
    backgroundImg: "FCCORPElectronics.jpg",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
  },
  {
    id: 14,
    name: "MyWay",
    details: `תחבורהההה`,
    img: "facebook.jpg",
    backgroundImg: "MyWay.jpg",
    Technology: ["Wordpress", "HTML5", "CSS3", "Bootstrap", "PHP"],
    Link: "https://mywy.co.il/",
  },
];

export default data;
