let data = [
  {
    id: 1,
    name: "Apartments APP",
    details: `On the Backend I used Puppeteer to scrape the site "YAD2" with Proxy. Im saving the data in Mongodb server .On the front End Im getting the data from Mongodb and send queries to retrieve specific data`,
    img: "facebook.jpg",
    backgroundImg: "Apartments.png",
    Technology: [
      "NextJS",
      "HTML5",
      "CSS3",
      "MongoDB",
      "Puppeteer",
      "Material-UI",
    ],
    Link: "https://next-js-apartments.vercel.app/",
    Git: "https://github.com/tevelmantsur/NextJs-Apartments",
  },
  {
    id: 2,
    name: "Anime APP",
    img: "facebook.jpg",
    backgroundImg: "AnimeApp.jpg",
    Technology: ["React", "HTML5", "CSS3"],
    Link: "https://young-falls-71941.herokuapp.com/",
    Git: "https://github.com/tevelmantsur/Movies-APP--react",
  },

  {
    id: 3,
    name: "Tevel Develepoment",
    details: `This project is my portfolio, it shows all my works and my ideas and it also has all the details about me.
    Built with lots of love using React`,
    img: "facebook.jpg",
    backgroundImg: "TevelDEV.png",
    Technology: ["React", "HTML5", "CSS3"],
    Link: "https://teveldevelopment.netlify.app/",
    Git: "https://github.com/tevelmantsur/Portfolio-React",
  },
  {
    id: 4,
    name: "Tree APP",
    img: "facebook.jpg",
    backgroundImg: "MagenTrees.png",
    mobile: true,
    Technology: ["React-Native", "Expo", "LiteSQL"],
  },
  {
    id: 5,
    name: "HELEN TZUR",
    img: "facebook.jpg",
    backgroundImg: "HelenPage.png",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
  },
  {
    id: 6,
    name: "DUBI BUS",
    img: "dubibus.png",
    backgroundImg: "dubibus.png",
    Technology: ["Wordpress", "HTML5"],
    Link: "https://dubbus.co.il/",
  },
  {
    id: 7,
    name: "DUBI TOURS",
    img: "dubitours.png",
    backgroundImg: "dubitours.png",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
    Link: "https://dubitours.co.il/",
  },
  {
    id: 8,
    name: "SELVA RESORT",
    img: "selvaresort.png",
    backgroundImg: "selvaresort.png",
    Technology: ["Wix", "HTML5", "CSS3"],
    Link: "https://www.selvaresort.com/",
  },
  {
    id: 9,
    name: "SUPER FIT",
    img: "24fitclub.png",
    backgroundImg: "SuperfitPage.jpg",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
  },
  {
    id: 10,
    name: "CANNA YAGODA",
    img: "cannayagoda.png",
    backgroundImg: "CannayagodaPage.jpg",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
    Link: " https://cannayagoda.co.il/?lang=en",
  },
  {
    id: 11,
    name: "FLYCHIPS",
    img: "flychips.png",
    backgroundImg: "FlychipsPage.png",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
    Link: "https://flychips.com/",
  },
  {
    id: 12,
    name: "Yeshivot APP",
    img: "facebook.jpg",
    backgroundImg: "YeshivotAPP.jpg",
    mobile: true,
    Technology: ["React-Native", "Expo", "FireBase"],
  },

  {
    id: 13,
    name: "FC CORP Electronics",
    details: `C CORP. specializes in electronic components supply solutions as well as stock management for companies.
    The company is a global company in continuous growth and operates in countries around the world.`,
    img: "facebook.jpg",
    backgroundImg: "FCCORPElectronics.jpg",
    Technology: ["Wordpress", "HTML5", "CSS3", "PHP"],
  },
  {
    id: 14,
    name: "MyWay",
    img: "facebook.jpg",
    backgroundImg: "MyWay.jpg",
    Technology: ["Wordpress", "HTML5", "CSS3", "Bootstrap", "PHP"],
    Link: "https://mywy.co.il/",
  },
];

export default data;
